### PR TITLE
Added support for date_immutable and time_immutable field types.

### LINKED ISSUE #69: Add support for time_immutable and date_immutable
I'm trying to transition to using DateTimeImmutable, but getting stuck because DoctrineObject is missing support for  date_immutable and time_immutable. Would be great to have support added.
https://github.com/doctrine/doctrine-laminas-hydrator/blob/c8b6c2a85315b6742e569c477ee354dbfcfa6e74/src/DoctrineObject.php#L650

### PR DESCRIPTION
**Pull request by TomHAnderson**
Moved from #70 onto a different branch

@dkmuir

### CODE REVIEW

**Comment by dkmuir** [comment]
@TomHAnderson  Ah, apologies. First time contributing. I've fixed the 3 lines flagged by the codesniffer check. What's the right way to push that through?

**Comment by TomHAnderson** [comment]
@dkmuir The CS isn't your problem.  I've opened #73 to fix the underlying issue and will merge that first then rebase your commit.

**Comment by TomHAnderson** [comment]
@dkmuir To answer your question, a PR to my PR'd branch would be the way to do it.

**Comment by driehle** [comment]
Merged #73, would you mind rebasing?

**Review by driehle — APPROVED** [review]

**Pull request merged**
