### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by driehle**
This MR raises the minimum dependencies to their latest version

### CODE REVIEW

**Comment by greg0ire** [comment]
:thinking: what's the point of this?

**Comment by driehle** [comment]
> 🤔 what's the point of this?

Reducing potential incompatibilities, as CI only tests lowest and latest dependencies. Hence, the more far apart the lowest requirement in this project and the latest actual release are, the higher the risk of getting some issues.

The new lower bounds are all supported by PHP 8.0, so for me there is no reason in not raising the lower bounds.

**Comment by greg0ire** [comment]
Is this purely theoretical or based on an issue you observed where the CI was green but wouldn't have been if picking a version in the middle? I'm really not convinced about this reasoning, and even if I were, this is not the policy I've observed on other Doctrine repositories, except for development dependencies.

**Comment by TomHAnderson** [comment]
I agree with @greg0ire on this.  Unless this is to address an issue then raising the minimum requirements just reduces the footprint of compatibility.

**Comment by ostrolucky** [comment]
I agree with others as well, let's close.

**Pull request closed without merging**
