### PR TITLE
Updated scripts in composer.json

### PR DESCRIPTION
**Pull request by driehle**

### CODE REVIEW

**Comment by greg0ire** [comment]
Please improve your commit message according to [the contributing guide](https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches). In the present case, I have no idea why you would want to move psalm.xml to psalm.xml.dist

**Comment by driehle** [comment]
@greg0ire I considered this as self-explanatory, sorry 🤷‍♂️ 

I updated the commit message accordingly.

**Comment by greg0ire** [comment]
No worries. Why would a user want to override `psalm.xml.dist`?

**Comment by driehle** [comment]
We are doing the same for `psalm.xml.dist` and `phpunit.xml.dist` (accross all repositories, I think). Though I guess that most users (I am actually refering to developers here, not end users) won't override these files, there may be circumstances where it is helpful to override them. The same principle applies to `psalm.xml.dist`. We should probably rename `phpstan.neon` to `phpstan.neon.dist` as well though.

**Comment by greg0ire** [comment]
I can think of some reasons to do it for phpunit.xml on some repositories, but I'd be really interested to know how many people actually resort to it, or why you would need to do it in the case of Psalm.

I think it only complicates things as one might forget they once did it and wonder why they get different results locally or in the CI. Personally, the very rare times I've had to [use a different database](https://github.com/doctrine/orm/pull/8958), I've instead run `vendor/bin/phpunit -c ci/github/phpunit/oci8.xml`.

**Comment by driehle** [comment]
The only reason I could think of regarding Psalm is lowering the level locally to see the issues that should probably targeted in a next major. Anyways, I don't care that much, my idea was rather to have all build tools (i.e. PhpCS, PHPUnit, PHPStan and Psalm) consistent in terms of their configuration.

**Comment by driehle** [comment]
@greg0ire I updated the commit, let's keep `psalm.xml` for now.

**Review by greg0ire — APPROVED** [review]

**Pull request merged**
